const figures = [
{id:"kai-pilot",name:"Kai (Pilot)",character:"Kai",season:"Season 1",year:2011,rarity:"Rare",demand:"High",value:42,trend:"rising",change:"+8%",note:"Classic early Kai minifigure."},
{id:"jay-pilot",name:"Jay (Pilot)",character:"Jay",season:"Season 1",year:2011,rarity:"Uncommon",demand:"Medium",value:18,trend:"stable",change:"0%",note:"Original pilot-era Jay."},
{id:"cole-pilot",name:"Cole (Pilot)",character:"Cole",season:"Season 1",year:2011,rarity:"Uncommon",demand:"Low",value:14,trend:"dropping",change:"-3%",note:"Early Earth Ninja variant."},
{id:"zane-pilot",name:"Zane (Pilot)",character:"Zane",season:"Season 1",year:2011,rarity:"Rare",demand:"Medium",value:25,trend:"stable",change:"+1%",note:"Original white ninja design."},
{id:"lloyd-golden",name:"Golden Lloyd",character:"Lloyd",season:"Season 2",year:2012,rarity:"Mythical",demand:"Very High",value:250,trend:"rising",change:"+12%",note:"One of the most iconic collector minifigures."},
{id:"garmadon-sensei",name:"Sensei Garmadon",character:"Garmadon",season:"Season 2",year:2012,rarity:"Epic",demand:"High",value:68,trend:"rising",change:"+5%",note:"Classic Garmadon from the early era."},
{id:"overlord",name:"Overlord",character:"Overlord",season:"Season 2",year:2012,rarity:"Legendary",demand:"Very High",value:110,trend:"rising",change:"+10%",note:"Highly desirable final villain form."},
{id:"nya-samurai",name:"Samurai X Nya",character:"Nya",season:"Season 3",year:2014,rarity:"Rare",demand:"Medium",value:32,trend:"stable",change:"0%",note:"Armoured Samurai X identity."},
{id:"pixal-original",name:"P.I.X.A.L.",character:"Pixal",season:"Season 3",year:2014,rarity:"Epic",demand:"High",value:54,trend:"rising",change:"+4%",note:"Original android appearance."},
{id:"zane-titanium",name:"Titanium Zane",character:"Zane",season:"Season 4",year:2015,rarity:"Epic",demand:"High",value:74,trend:"rising",change:"+7%",note:"Fan-favourite titanium redesign."},
{id:"chen",name:"Master Chen",character:"Chen",season:"Season 4",year:2015,rarity:"Legendary",demand:"Medium",value:80,trend:"stable",change:"+1%",note:"Tournament villain."},
{id:"morro",name:"Morro",character:"Morro",season:"Season 5",year:2015,rarity:"Legendary",demand:"Very High",value:145,trend:"rising",change:"+15%",note:"Extremely popular ghost villain."},
{id:"nadakhan",name:"Nadakhan",character:"Nadakhan",season:"Season 6",year:2016,rarity:"Legendary",demand:"High",value:98,trend:"stable",change:"+2%",note:"Skybound's flagship villain."},
{id:"kai-skybound",name:"Skybound Kai",character:"Kai",season:"Season 6",year:2016,rarity:"Rare",demand:"Medium",value:29,trend:"dropping",change:"-2%",note:"Skybound ninja uniform."},
{id:"time-twins",name:"Acronix",character:"Acronix",season:"Season 7",year:2017,rarity:"Epic",demand:"Medium",value:52,trend:"stable",change:"0%",note:"Time Twins villain."},
{id:"harumi",name:"Harumi",character:"Harumi",season:"Season 8",year:2018,rarity:"Epic",demand:"Very High",value:88,trend:"rising",change:"+11%",note:"One of the most demanded villains."},
{id:"mystake",name:"Mystake",character:"Mystake",season:"Season 9",year:2018,rarity:"Legendary",demand:"High",value:105,trend:"rising",change:"+6%",note:"Limited and distinctive minifigure."},
{id:"golden-kai",name:"Golden Kai",character:"Kai",season:"Season 10",year:2019,rarity:"Mythical",demand:"Insane",value:320,trend:"rising",change:"+18%",note:"Premium golden ninja variant."},
{id:"prime-empire-jay",name:"Prime Empire Jay",character:"Jay",season:"Season 12",year:2020,rarity:"Rare",demand:"Low",value:16,trend:"dropping",change:"-5%",note:"Arcade-themed ninja outfit."},
{id:"island-lloyd",name:"Island Lloyd",character:"Lloyd",season:"The Island",year:2021,rarity:"Common",demand:"Very Low",value:6,trend:"stable",change:"0%",note:"Widely available Island variant."},
{id:"seabound-nya",name:"Seabound Nya",character:"Nya",season:"Season 14",year:2021,rarity:"Epic",demand:"High",value:63,trend:"rising",change:"+9%",note:"Popular Seabound design."}
];